---
title: "Suivis hydrobiologiques"
author: "DR OFB Île-de-France"
date: "`r Sys.Date()`"
output: 
  html_document :
    highlight: pygments 
    theme: flatly 
    css: "theme_html2.css"
# Language
lang: fr-FR
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE, echo=FALSE, warning=FALSE, message = FALSE)
import::from("magrittr", "%>%")
```

```{r}
load("../data/referentiels.rda")
purrr::walk(
  list.files(path = "../scripts", pattern = ".R", full.names = TRUE),
  source
)

codes_departements <- c(75,77,78,91,92,93,94,95)
codes_departements_extra <- c(10, 52)

choix_eqb <- list(
  "Poissons", "Macroinvertébrés", "Diatomées", "Macrophytes",
  c("Poissons", "Macroinvertébrés", "Diatomées", "Macrophytes"),
  c("Macroinvertébrés", "Diatomées", "Macrophytes")
)
codes_indices <- c(2928,5856,5910,7613,6951,7036) #IBMR, IBD, IBG-équivalent, I2M2, Indice invertébrés grand cours d'eau, IPR
```

```{r}
openxlsx2::read_xlsx("../data/labo/Historique prog labo.xlsx") %>%
  janitor::clean_names() %>%
  (function(df_xl) {
    indices <- df_xl[1,-seq(3)] %>%
      t() %>%
      as.vector() %>%
      unique()

    purrr::map_dfr(
      indices,
      function(i) {
        df_xl[-1,c(seq(3), which(as.vector(t(df_xl[1,])) == i))] %>%
          tidyr::pivot_longer(
            cols = -seq(3),
            names_to = "annee",
            values_to = "realisation"
          ) %>%
          dplyr::mutate(
            annee = annee %>%
              stringr::str_extract_all(
                pattern = "\\d{4}"
              ) %>%
              as.numeric(),
            indice = i,
            code_station = paste0("0", code_station)
          ) %>%
          dplyr::filter(realisation == "X") %>%
          dplyr::select(
            cours_deau, commune, code_station, indice, annee, realisation
          )
      }
    ) %>%
      dplyr::mutate(
        code_indice = dplyr::case_when(
          indice == "IBD" ~ "5856",
          indice == "MPCE" ~ "5910",
          indice == "IBMR" ~ "2928"
        )
      ) %>%
      (function(df) {
        dplyr::bind_rows(
          df,
          df %>%
            dplyr::filter(indice == "MPCE") %>%
            dplyr::mutate(code_indice = "7613")
        )
      })

  }) %>%
  saveRDS(file = "../data/operations_labo.rds")

suivi_regie <- readRDS("../data/operations_labo.rds")
```

```{r}
to_update <- check_updates(
  codes_departements = codes_departements,
  codes_departements_extra = codes_departements_extra,
  code_indice = codes_indices,
  limites_zone = limites_sn,
  suivi_regie = suivi_regie,
  dest_folder = "../data"
)
  
```

```{r}
if (to_update) {
  telecharger_stations(
    code_departement = c(codes_departements, codes_departements_extra),
    limites_zone = limites_sn,
    suivi_regie = suivi_regie
    ) %>%
    dplyr::filter(code_departement %in% codes_departements |  regie) %>% 
    (function(stations) {
      stations %>% 
        saveRDS(file = "../data/stations_hydrobio.rds")
      
      stations %>%
        sf::st_transform(crs = 4326) %>%
        sf::st_bbox() %>%
        saveRDS(file = "../data/bbox_stations.rds")
    })
    
  stations_hydrobio <- readRDS("../data/stations_hydrobio.rds")
  
  telecharger_indices(
    code_departement = c(codes_departements, codes_departements_extra),
    code_indice = codes_indices,
    limites_zone = limites_sn,
    suivi_regie = suivi_regie
  ) %>%
    dplyr::filter(
      code_station_hydrobio %in% stations_hydrobio$code_station_hydrobio
      ) %>% 
    saveRDS(file = "../data/indices_hydrobio.rds")
  
  indices_hydrobio <- readRDS("../data/indices_hydrobio.rds")
  
  prep_data_carte(
    stations = stations_hydrobio,
    indices = indices_hydrobio,
    liste_eqb = choix_eqb
  ) %>%
    saveRDS(file = "../data/stations_sf.rds")
  
  prep_data_graph(
    stations = stations_hydrobio,
    indices = indices_hydrobio,
    suivi_regie = suivi_regie
  ) %>%
    saveRDS(file = "../data/data_graphs.rds")
  
  donnees_popup <- readRDS("../data/data_graphs.rds")
  
  prep_popups(
    donnees_popups = donnees_popup,
    dest_folder = "../www/popups"
  )
}

```


```{r}
stations_sf <- readRDS("../data/stations_sf.rds")
bbox_stations <- readRDS("../data/bbox_stations.rds")

couleurs_etat <- c(
  `indéterminé` = "#CDC0B0",
  mauvais = "#EE2C2C",
  `médiocre` = "#FF7F00",
  moyen = "#FFC125",
  bon = "#A2CD5A",
  `très bon` = "#1874CD"
)

popups_indices <- file.path(
  "www/popups",
  list.files(path = "../www/popups", pattern = ".png") 
  ) %>% 
     (function(x) {
      names(x) <- x %>% 
        stringr::str_remove_all(pattern = "www/popups/") %>% 
        stringr::str_remove_all(pattern = ".png")
      
      x
    })

```

```{r, include=TRUE}
shared_stations <- crosstalk::SharedData$new(stations_sf %>% 
      dplyr::select(EQB, libelle_station, taille_symbole, colour_eqb, colour))

limites_sn_l <- limites_sn %>% 
      sf::st_cast(to = "LINESTRING") %>% 
  sf::st_transform(crs = 4326)
limites_idf_l <- limites_idf %>% 
      sf::st_cast(to = "LINESTRING") %>% 
  sf::st_transform(crs = 4326)
```

:::: {style="display: flex;"}

::: {style="flex-basis: 53%;"}

##

```{r, include=TRUE, out.width='100%', out.height='500px'}

  leaflet::leaflet() %>% 
    leaflet::addMapPane("background", zIndex = 400) %>% 
    leaflet::addMapPane("masks", zIndex = 450) %>% 
    leaflet::addMapPane("foreground", zIndex = 500) %>% 
    leaflet::addPolygons(
      data = edl_2022 %>% 
      dplyr::mutate(
        LABEL = paste0(NOM.MASSE.D.EAU, "<br>", ETAT.BIOLOGIQUE)
      ) %>% 
      dplyr::select(LABEL, ETAT.BIOLOGIQUE),
      group = "Etat biologique 2022",
      fillColor = ~unname(couleurs_etat[as.character(ETAT.BIOLOGIQUE)]),
      fillOpacity = .5,
      label = ~LABEL,
      popup = FALSE,
      weight = 1,
      options = leaflet::pathOptions(pane = "background")
    ) %>% 
    leaflet::addPolygons(
      data = edl_2022 %>% 
      dplyr::mutate(
        LABEL = paste0(NOM.MASSE.D.EAU, "<br>", ETAT.ECOLOGIQUE)
      ) %>% 
      dplyr::select(LABEL, ETAT.ECOLOGIQUE),
      group = "Etat écologique 2022",
      fillColor = ~unname(couleurs_etat[as.character(ETAT.ECOLOGIQUE)]),
      fillOpacity = .5,
      label = ~LABEL,
      popup = FALSE,
      weight = 1,
      options = leaflet::pathOptions(pane = "background")
    ) %>% 
    leaflet::addPolygons(
      data = edl_2022 %>% 
      dplyr::mutate(
        LABEL = paste0(NOM.MASSE.D.EAU, "<br>", ETAT.PHYSICO.CHIMIQUE)
      ) %>% 
      dplyr::select(LABEL, ETAT.PHYSICO.CHIMIQUE),
      group = "Etat physico-chimique 2022",
      fillColor = ~unname(couleurs_etat[as.character(ETAT.PHYSICO.CHIMIQUE)]),
      fillOpacity = .5,
      label = ~LABEL,
      popup = FALSE,
      weight = 1,
      options = leaflet::pathOptions(pane = "background")
    ) %>% 
    #     mapview::mapview(
    #   reseau_hydro,
    #   layer.name = "Réseau hydrographique",
    #   legend = FALSE,
    #   homebutton = FALSE,
    #   col.regions = "#00B2EE",
    #   cex = 1,
    #   label = "TopoOH",
    #   popup = FALSE
    # ) +
    leaflet::addPolylines(
      data = reseau_hydro,
      group = "Réseau hydrographique",
      color = "#00B2EE",
      weight = 1,
      label = ~TopoOH,
      popup = FALSE,
      opacity = 1,
      options = leaflet::pathOptions(pane = "background")
    ) %>% 
    leaflet::addPolygons(
      data = masque_metropole,
      fillColor = "white",
      fillOpacity = .75,
      stroke = FALSE,
      popup = FALSE, label = FALSE,
      options = leaflet::pathOptions(pane = "masks")
    ) %>% 
    leaflet::addPolylines(
      data = limites_sn_l, 
      color = "black",
      opacity = 1,
      weight = 2,
      options = leaflet::pathOptions(pane = "masks")
      ) %>% 
    leaflet::addPolylines(
      data = limites_idf_l, 
      color = "black",
      opacity = 1,
      weight = 2,
      options = leaflet::pathOptions(pane = "masks")
      ) %>% 
    leaflet::addCircleMarkers(
      data = shared_stations,
      group = "Indices",
      # legend = FALSE,
      label = ~libelle_station,
      popup = leafpop::popupImage(
        popups_indices[stations_sf$code_station_hydrobio],
        height = 360, width = 540, embed = FALSE
        ),
      popupOptions = leaflet::popupOptions(
        maxWidth = 540, maxHeight = 360
      ),
      radius = ~taille_symbole,
      fillColor = ~colour_eqb,
      color = ~colour,
      weight = 2,
      opacity = 1,
      fillOpacity = 0.75,
      options = leaflet::pathOptions(pane = "foreground")
      ) %>%
  leaflet::addTiles(group = "OSM") %>%
  #addProviderTiles(providers$CartoDB.PositronOnlyLabels, group = "Villes") %>% 
  leaflet::addTiles("http://wxs.ign.fr/choisirgeoportail/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&FORMAT=image/png&LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}",
           options = c(leaflet::WMSTileOptions(tileSize = 256),
                       leaflet::providerTileOptions(minZoom = 1, maxZoom = 15)),
           attribution='<a target="_blank" href="https://www.geoportail.gouv.fr/">Geoportail France</a>',
           group = "Plan IGN"
  ) %>%
  leaflet::addTiles("http://wxs.ign.fr/choisirgeoportail/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&STYLE=normal&TILEMATRIXSET=PM&FORMAT=image/jpeg&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}",
           options = c(leaflet::WMSTileOptions(tileSize = 256),
                       leaflet::providerTileOptions(minZoom = 1, maxZoom = 22)),
           attribution='<a target="_blank" href="https://www.geoportail.gouv.fr/">Geoportail France</a>',
           group = "Photo aérienne"
  ) %>%
  leaflet::addLayersControl(
    baseGroups    = c("OSM","Plan IGN","Photo aérienne",  "Etat écologique 2022","Etat biologique 2022", "Etat physico-chimique 2022"),
    overlayGroups = c("Réseau hydrographique", "Indices"),
    options       = leaflet::layersControlOptions(collapsed = TRUE)) %>% 
    leaflet::addLegend(
      title = "EQB suivis",
      position = "bottomleft",
      colors = viridisLite::viridis(n = 4)[4:1],
      labels = 4:1
    ) %>% 
    leaflegend::addLegendSize(
      title = htmltools::HTML("Années<br>de suivi"),
      shape = "circle",
      values = c(4, 6, 8, 12),
      color = "black",
      fillColor = "white",
      fillOpacity = 0,
      orientation = "vertical",
      position = "bottomleft",
      numberFormat = function(x) {
        dplyr::case_when(
          x == 4 ~ "1",
          x == 6 ~ "2-5",
          x == 8 ~ "6-10",
          x == 12 ~ "> 10"
        )
      },
        breaks = c(4, 6, 8, 12),
      baseSize = 15
    ) %>% 
    leaflet::fitBounds(
      lng1 = bbox_stations[["xmin"]],
      lat1 = bbox_stations[["ymin"]],
      lng2 = bbox_stations[["xmax"]],
      lat2 = bbox_stations[["ymax"]]
    ) %>% 
    leaflet.extras::addResetMapButton()
```

:::

::: {style="flex-basis: 1%;"}

:::

::: {style="flex-basis: 46%;"}

## {.tabset .tabset-pills}

### Chroniques

```{r, include=TRUE, out.width='100%'}
source("../scripts/plot_chroniques.R")
data_graphs <- readRDS("../data/data_graphs.rds")

plot_chroniques(stations_sf, data_graphs, interactive = TRUE)
```

### ...

:::

::::
```{r, include=TRUE}
crosstalk::bscols(
  crosstalk::filter_select(
    id = "eqb",
    label = "EQB",
    sharedData = shared_stations, 
    group = ~EQB,
    multiple = FALSE, 
    allLevels = FALSE,
    selected = "Poissons, Macroinvertébrés, Diatomées, Macrophytes"
    )
)

```

```{r, eval=FALSE}
get_taxa_counts <- function(indices, cd_support, max_prel = 200) {
  indices %>% 
    dplyr::filter(code_support == cd_support) %>% 
    dplyr::pull(code_prelevement) %>% 
    unique() %>% 
    (function(x) {
      split(
        x,
        ceiling(seq_along(x)/max_prel)
        )
      }) %>% 
    purrr::map_df(
      function(CdPrel) {
        hubeau::get_hydrobio_taxons(
          list(
            code_prelevement = paste(CdPrel, collapse = ",")
          )
        ) %>% 
        dplyr::group_by(
          code_station_hydrobio, code_prelevement, date_prelevement,
          code_appel_taxon, libelle_appel_taxon
        ) %>% 
        dplyr::summarise(resultat_taxon = sum(resultat_taxon), .groups = "drop")
      }
    )
}
```

```{r, eval=FALSE}
taxons_invertebres <- get_taxa_counts(indices_hydrobio, cd_support = 13)
taxons_diatomees   <- get_taxa_counts(indices_hydrobio, cd_support = 10)
taxons_macrophytes <- get_taxa_counts(indices_hydrobio, cd_support = 27)
taxons_poissons    <- get_taxa_counts(indices_hydrobio, cd_support = 4)
```

```{r, eval=FALSE}
plot_number_taxa <- function(taxons, ..., group) {
  taxons %>% 
    dplyr::group_by(...) %>% 
    dplyr::summarise(nb_taxons = dplyr::n_distinct(libelle_appel_taxon), .groups = "drop") %>% 
    ggplot2::ggplot(mapping = ggplot2::aes(y = nb_taxons, fill = {{group}})) +
    ggplot2::geom_boxplot()
}
```

```{r, eval=FALSE}
(plot_number_taxa(
  taxons = dplyr::bind_rows(
    dplyr::mutate(taxons_diatomees, groupe = "diatomées"),
    dplyr::mutate(taxons_macrophytes, groupe = "macrophytes"),
    dplyr::mutate(taxons_invertebres, groupe = "invertébres"),
    dplyr::mutate(taxons_poissons, groupe = "poissons")
  ),
  code_station_hydrobio, groupe,
  group = groupe
)
)
```

