on:
  schedule:
    - cron:  "0 5 * * *"
  workflow_dispatch:

name: script_R

jobs:
  run-r-script:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1' # Pandoc version pour compiler.

      - name: Installation packages
        run: |
          Rscript "install_dep.R"

      - name: Rendu page
        run: |
          Rscript "render_page.R"

      - name: Commit Results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script $(date)" || echo "No changes to commit"
          git push origin -f || echo "No changes to commit"-

